FROM artifactory.apps.bancolombia.com/devops/openshift/vault:1.3.1 as vault

FROM artifactory.apps.bancolombia.com/evc/latest/elixir:1.13.3-alpine as build_image
ARG AUTH_TOKEN_HEADER
ENV MIX_ENV=prod
WORKDIR /app
RUN apk add build-base git && mix local.hex --force && mix local.rebar --force
COPY mix.exs mix.lock ./
RUN git config --global http.https://dev.azure.com/GrupoBancolombia/.extraheader "${AUTH_TOKEN_HEADER}"
RUN mix deps.get && mix deps.compile
COPY . .
RUN mix distillery.release

FROM artifactory.apps.bancolombia.com/evc/latest/elixir:1.13.3-alpine
ENV MIX_ENV=prod
USER root
WORKDIR /app
EXPOSE 8081 8082
RUN apk update && apk upgrade && apk add bash
COPY --from=vault --chown=appuser /bin/vault /bin/vault
COPY --chown=appuser ./resources/docker/init.sh /app/
COPY --from=build_image --chown=appuser /app/_build/prod /app
RUN chown -R appuser /app \
    && chmod -R 777 /app \
    && mkdir /vault \
    && chown appuser /vault \
    && chmod 777 /vault \
    && mkdir /percona \
    && chown appuser /percona \
    && chmod 777 /percona \
    && chmod -R 777 /app \
    && chown appuser /app/init.sh \
    && chmod 777 /app/init.sh \
    && mkdir /config \
    && chown appuser /config \
    && chmod "g+rwX" /config \
    && chown appuser:root /config

USER appuser
ENTRYPOINT [ "sh", "-c", "vault agent -config=/vault/config/agent-config.hcl && /app/init.sh"]