apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    app: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}-autoscaling
spec:
  maxReplicas: ${MAX-REPLICAS}
  minReplicas: ${REPLICAS}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APPLICATION_NAME}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${TARGET-CPU}